/**
 * Canonical seed for the government tracker.
 * Idempotent upserts — safe to run on every scrape if the cabinet table is empty.
 * Facts are sourced from public reporting (Rudaw, 964, Shafaq, Al Jazeera, Atlantic).
 */

export type SeedOfficial = {
  slug: string
  name_ar: string
  name_en: string
  title_ar: string
  title_en: string
  role_type: 'prime_minister' | 'deputy_pm' | 'minister' | 'mp' | 'speaker' | 'other'
  party_ar: string | null
  party_en: string | null
  ministry_ar: string | null
  ministry_en: string | null
  bio_ar: string | null
  bio_en: string | null
  twitter_handle: string | null
  term_start: string
  is_active: boolean
}

export type SeedKpi = {
  official_slug: string
  title_ar: string
  title_en: string
  description_ar: string
  description_en: string
  category: 'economy' | 'infrastructure' | 'security' | 'corruption' | 'healthcare' | 'education' | 'services' | 'general'
  status: 'promised' | 'in_progress' | 'achieved' | 'failed' | 'abandoned' | 'stalled'
  date_promised: string
  deadline: string | null
  source_url: string
  notes_ar?: string
  notes_en?: string
}

export type SeedMetric = {
  slug: string
  name_ar: string
  name_en: string
  description_ar: string
  description_en: string
  value: number
  unit: string
  year: number
  global_rank?: number | null
  total_countries?: number | null
  previous_value?: number | null
  trend?: 'up' | 'down' | 'stable' | null
  category: 'economy' | 'governance' | 'social' | 'security' | 'infrastructure'
  source_name: string
  source_url: string
}

export type SeedCase = {
  official_slug: string | null
  title_ar: string
  title_en: string
  description_ar: string
  description_en: string
  amount_usd: number | null
  date_reported: string
  source_urls: string[]
  status: 'alleged' | 'under_investigation' | 'confirmed' | 'acquitted' | 'convicted' | 'dismissed'
  evidence_level: 'low' | 'medium' | 'high' | 'documented'
  case_type: 'financial' | 'bribery' | 'embezzlement' | 'nepotism' | 'abuse_of_power' | 'other'
  is_published: boolean
}

export const SEED_OFFICIALS: SeedOfficial[] = [
  {
    slug: 'ali-al-zaidi',
    name_ar: 'علي فالح كاظم الزيدي',
    name_en: 'Ali Faleh al-Zaidi',
    title_ar: 'رئيس مجلس الوزراء',
    title_en: 'Prime Minister',
    role_type: 'prime_minister',
    party_ar: 'الإطار التنسيقي',
    party_en: 'Coordination Framework',
    ministry_ar: null,
    ministry_en: null,
    bio_ar: 'رجل أعمال ومصرفي، وُلد في ١ مايو ١٩٨٥. أصغر رئيس وزراء في تاريخ العراق. كُلِّف بتشكيل الحكومة في ٢٧ أبريل ٢٠٢٦ ونال ثقة البرلمان جزئياً في ١٤ مايو ٢٠٢٦ — ١٤ حقيبة من أصل ٢٣. تعهّد بتنويع الاقتصاد ومكافحة الفساد وخدمة دورة واحدة.',
    bio_en: 'Banker and businessman, born 1 May 1985. Iraq’s youngest prime minister. Tasked with forming a government on 27 April 2026; sworn in 14 May 2026 with 14 of 23 portfolios filled. Pledged economic diversification, an anti-corruption drive, and a single four-year term.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'nizar-amidi',
    name_ar: 'نزار محمد أميدي',
    name_en: 'Nizar Amidi',
    title_ar: 'رئيس الجمهورية',
    title_en: 'President of Iraq',
    role_type: 'other',
    party_ar: 'الاتحاد الوطني الكردستاني',
    party_en: 'Patriotic Union of Kurdistan (PUK)',
    ministry_ar: null,
    ministry_en: null,
    bio_ar: 'سياسي كردي عراقي من حزب الاتحاد الوطني الكردستاني. انتُخب رئيساً للجمهورية في ١١ أبريل ٢٠٢٦.',
    bio_en: 'Kurdish Iraqi politician from the PUK. Elected President of Iraq on 11 April 2026, succeeding Abdul Latif Rashid.',
    twitter_handle: null,
    term_start: '2026-04-11',
    is_active: true,
  },
  {
    slug: 'haibat-al-halbousi',
    name_ar: 'هيبت حمد عباس الحلبوسي',
    name_en: 'Haibat al-Halbousi',
    title_ar: 'رئيس مجلس النواب',
    title_en: 'Speaker of Parliament',
    role_type: 'speaker',
    party_ar: 'تقدم',
    party_en: 'Taqaddum Party',
    ministry_ar: null,
    ministry_en: null,
    bio_ar: 'سياسي سني عراقي. رأس لجنة النفط والطاقة ٢٠١٩–٢٠٢٥. انتُخب رئيساً للبرلمان في ٢٩ ديسمبر ٢٠٢٥. التقى وزير المالية لمناقشة موازنة ٢٠٢٧ بينما العراق بلا موازنة لعام ٢٠٢٦.',
    bio_en: 'Iraqi Sunni politician. Chaired the Oil and Energy Committee 2019–2025. Elected Speaker on 29 December 2025. Has met the finance minister on the 2027 budget while Iraq operates with no 2026 budget at all.',
    twitter_handle: null,
    term_start: '2025-12-29',
    is_active: true,
  },
  {
    slug: 'adnan-fayhan',
    name_ar: 'عدنان فيحان',
    name_en: 'Adnan Fayhan',
    title_ar: 'النائب الأول لرئيس البرلمان',
    title_en: 'First Deputy Speaker',
    role_type: 'other',
    party_ar: null,
    party_en: null,
    ministry_ar: null,
    ministry_en: null,
    bio_ar: 'انتُخب نائباً أول لرئيس مجلس النواب في ٢٩ ديسمبر ٢٠٢٥.',
    bio_en: 'Elected First Deputy Speaker of the Council of Representatives on 29 December 2025.',
    twitter_handle: null,
    term_start: '2025-12-29',
    is_active: true,
  },
  {
    slug: 'fuad-hussein',
    name_ar: 'فؤاد محمد حسين',
    name_en: 'Fuad Mohammed Hussein',
    title_ar: 'وزير الخارجية',
    title_en: 'Minister of Foreign Affairs',
    role_type: 'minister',
    party_ar: 'الحزب الديمقراطي الكردستاني',
    party_en: 'Kurdistan Democratic Party (KDP)',
    ministry_ar: 'وزارة الخارجية',
    ministry_en: 'Foreign Affairs',
    bio_ar: 'سياسي كردي، شغل منصب وزير الخارجية منذ ٢٠٢٠ واحتفظ به في حكومة الزيدي.',
    bio_en: 'Kurdish politician. Foreign minister since 2020; retained the portfolio in the Zaidi cabinet.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'faleh-sari',
    name_ar: 'فالح ساري',
    name_en: 'Falih al-Sari',
    title_ar: 'وزير المالية',
    title_en: 'Minister of Finance',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة المالية',
    ministry_en: 'Finance',
    bio_ar: 'وزير مالية حكومة الزيدي. يدير إنفاقاً بلا موازنة اتحادية لعام ٢٠٢٦، تحت قاعدة «الجزء من اثني عشر»، في سنة سجّل فيها النصف الأول عجزاً يفوق ١٦ مليار دولار.',
    bio_en: 'Finance minister in the Zaidi government. Running 2026 spending under the one-twelfth rule with no approved federal budget, after a first-half deficit above $16 billion.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'basim-mohammed',
    name_ar: 'باسم محمد',
    name_en: 'Basim Mohammed',
    title_ar: 'وزير النفط',
    title_en: 'Minister of Oil',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة النفط',
    ministry_en: 'Oil',
    bio_ar: 'وزير النفط في حكومة الزيدي. يواجه انهيار صادرات الخام عبر مضيق هرمز: نحو ٥٢٦ ألف برميل يومياً في مايو–يونيو ٢٠٢٦ مقابل نحو ٣٫٣ مليون قبل الأزمة.',
    bio_en: 'Oil minister in the Zaidi government. Facing a collapse in crude exports via the Strait of Hormuz: about 526,000 barrels per day in May–June 2026 versus ~3.3 million before the crisis.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'ali-saad-wahib',
    name_ar: 'علي سعد وهيب',
    name_en: 'Ali Saad Wahib',
    title_ar: 'وزير الكهرباء',
    title_en: 'Minister of Electricity',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الكهرباء',
    ministry_en: 'Electricity',
    bio_ar: 'وزير الكهرباء. الحقيبة من أضخم بنود الدعم التشغيلي في موازنة ريعية بلا إصلاح هيكلي معلن للتعرفة أو الفاقد.',
    bio_en: 'Electricity minister. The portfolio is one of the largest operational subsidy lines in a rentier budget with no published structural tariff reform.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'abdulhussein-aziz',
    name_ar: 'عبدالحسين عزيز',
    name_en: 'Abdulhussein Aziz',
    title_ar: 'وزير الصحة',
    title_en: 'Minister of Health',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الصحة',
    ministry_en: 'Health',
    bio_ar: 'وزير الصحة في حكومة الزيدي، المؤكَّد في ١٤ مايو ٢٠٢٦.',
    bio_en: 'Minister of Health in the Zaidi government, confirmed 14 May 2026.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'sarwa-abdulwahid',
    name_ar: 'سروة عبدالواحد',
    name_en: 'Sarwa Abdulwahid',
    title_ar: 'وزيرة البيئة',
    title_en: 'Minister of Environment',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة البيئة',
    ministry_en: 'Environment',
    bio_ar: 'المرأة الوحيدة في حكومة الزيدي حتى تشكيلها الجزئي في مايو ٢٠٢٦.',
    bio_en: 'The only woman in the Zaidi cabinet as of the partial confirmation in May 2026.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'abdulrahim-jassim',
    name_ar: 'عبدالرحيم جاسم',
    name_en: 'Abdulrahim Jassim',
    title_ar: 'وزير الزراعة',
    title_en: 'Minister of Agriculture',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الزراعة',
    ministry_en: 'Agriculture',
    bio_ar: 'وزير الزراعة. الزراعة أحد أعمدة خطاب التنويع — وحصة الاستثمار الحقيقي في النصف الأول من ٢٠٢٦ كانت ٢٫٥ تريليون دينار فقط من إنفاق يتجاوز ٥٧ تريليوناً.',
    bio_en: 'Minister of Agriculture. Farming is a pillar of the diversification speech — while H1 2026 investment spending was only IQD 2.5 trillion of more than IQD 57 trillion total.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'muthanna-al-tamimi',
    name_ar: 'مثنى علي مهدي التميمي',
    name_en: 'Muthanna al-Tamimi',
    title_ar: 'وزير الموارد المائية',
    title_en: 'Minister of Water Resources',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الموارد المائية',
    ministry_en: 'Water Resources',
    bio_ar: 'وزير الموارد المائية في حكومة الزيدي.',
    bio_en: 'Minister of Water Resources in the Zaidi government.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'khalid-shwani',
    name_ar: 'خالد شواني',
    name_en: 'Khalid Shwani',
    title_ar: 'وزير العدل',
    title_en: 'Minister of Justice',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة العدل',
    ministry_en: 'Justice',
    bio_ar: 'احتفظ بحقيبة العدل في حكومة الزيدي.',
    bio_en: 'Retained the Justice portfolio in the Zaidi government.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'mohammed-nouri-ahmed',
    name_ar: 'محمد نوري أحمد',
    name_en: 'Mohammed Nouri Ahmed',
    title_ar: 'وزير الصناعة والمعادن',
    title_en: 'Minister of Industry & Minerals',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الصناعة والمعادن',
    ministry_en: 'Industry & Minerals',
    bio_ar: 'وزير الصناعة. خطاب التنويع يمر من هنا — والأرقام التشغيلية ما زالت تبتلع الاستثمار.',
    bio_en: 'Industry minister. Diversification rhetoric runs through this ministry — operational spending still crowds out investment.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
  {
    slug: 'mustafa-jabbar-sanad',
    name_ar: 'مصطفى جبار سند',
    name_en: 'Mustafa Jabbar Sanad',
    title_ar: 'وزير الاتصالات',
    title_en: 'Minister of Communications',
    role_type: 'minister',
    party_ar: null,
    party_en: null,
    ministry_ar: 'وزارة الاتصالات',
    ministry_en: 'Communications',
    bio_ar: 'وزير الاتصالات في حكومة الزيدي.',
    bio_en: 'Minister of Communications in the Zaidi government.',
    twitter_handle: null,
    term_start: '2026-05-14',
    is_active: true,
  },
]

export const SEED_SESSION = {
  session_number: 1,
  term_number: 6,
  title_ar: 'الدورة الأولى — الفصل التشريعي السادس',
  title_en: 'First Session — Sixth Parliamentary Term',
  start_date: '2025-12-29',
  status: 'active',
  laws_passed: 0,
  sessions_held: 0,
  description_ar: 'الفصل التشريعي السادس لمجلس النواب (٣٢٩ مقعداً). الجلسة الأولى في ٢٩ ديسمبر ٢٠٢٥. البرلمان تجاوز موازنة ٢٠٢٦ ليركّز على ٢٠٢٧، تاركاً الإنفاق تحت قاعدة الجزء من اثني عشر.',
  description_en: 'Sixth term of the Council of Representatives (329 seats). First session 29 December 2025. Parliament skipped a 2026 budget to concentrate on 2027, leaving spending under the one-twelfth rule.',
}

export const SEED_KPIS: SeedKpi[] = [
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'تنويع الاقتصاد والتحرر من الاعتماد على النفط',
    title_en: 'Economic diversification — reduce oil dependency',
    description_ar: 'تعهّد الزيدي في خطاب التكليف ببناء اقتصاد لا يعتمد على مورد واحد. في النصف الأول من ٢٠٢٦ بقي النفط نحو ٨٠٪ من الإيرادات الاتحادية بعد انهيار الصادرات — لا لأن الاقتصاد تنوّع، بل لأن النفط انكمش.',
    description_en: 'Zaidi pledged a diversified economy not dependent on a single resource. In H1 2026 oil was still ~80% of federal revenue after an export collapse — not because the real economy diversified, but because oil shrank.',
    category: 'economy',
    status: 'stalled',
    date_promised: '2026-05-16',
    deadline: '2026-12-31',
    source_url: 'https://shafaq.com/en/Iraq/Iraq-s-new-PM-pledges-economic-reform-anti-corruption-drive-in-first-address-to-nation',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'إقرار موازنة اتحادية لعام ٢٠٢٦',
    title_en: 'Pass a 2026 federal budget',
    description_ar: 'لا توجد موازنة اتحادية لعام ٢٠٢٦. البرلمان انتقل إلى ٢٠٢٧ والإنفاق يجري بقاعدة الجزء من اثني عشر من موازنة السنوات السابقة. دولة بلا قانون موازنة ليست دولة تخطط — إنها دولة تصرّف.',
    description_en: 'There is no 2026 federal budget. Parliament moved on to 2027; spending runs under the one-twelfth rule from prior years. A state without a budget law is not planning. It is disbursing.',
    category: 'economy',
    status: 'failed',
    date_promised: '2026-05-14',
    deadline: '2026-01-01',
    source_url: 'https://en.964media.com/51081/',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'ضبط فاتورة الرواتب والتزامات الدولة الشهرية',
    title_en: 'Stabilise the monthly public-salary bill',
    description_ar: 'مستشار رئيس الوزراء قدّر الالتزام الشهري بـ٧٫٧ تريليون دينار (نحو ٥٫٩ مليار دولار) يمسّ نحو ٤٠ مليون عراقي عبر الرواتب والرعاية. الحكومة أقرّت أزمة مالية في يوليو وأخّرت جداول الصرف.',
    description_en: 'The PM’s financial adviser put monthly state salary and related payments at IQD 7.7 trillion (~$5.9bn), touching some 40 million Iraqis. The government confirmed a fiscal crisis in July and staggered payroll.',
    category: 'economy',
    status: 'stalled',
    date_promised: '2026-05-16',
    deadline: '2026-12-31',
    source_url: 'https://en.964media.com/51739/',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'مكافحة الفساد المالي والإداري',
    title_en: 'Anti-corruption drive',
    description_ar: 'التزم بحماية المال العام. في يونيو نُفِّذت مداهمات في المنطقة الخضراء واعتُقل عشرات المسؤولين بينهم نائب وزير النفط. الرصد لا يساوي إدانة — لكنه يساوي اختباراً: هل تصل الملفات إلى أحكام أم تتوقف عند الكاميرات؟',
    description_en: 'Pledged to protect public funds. June Green Zone raids detained dozens of officials, including the deputy oil minister. Documentation is not conviction — but it is a test: do files reach verdicts, or stop at the cameras?',
    category: 'corruption',
    status: 'in_progress',
    date_promised: '2026-05-16',
    deadline: '2027-05-14',
    source_url: 'https://www.theatlantic.com/national-security/2026/07/iraq-ali-alzaidi-iran-war-trump/688009/',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'إصلاح البنية التحتية (كهرباء وماء وطرق وإسكان)',
    title_en: 'Infrastructure reform — power, water, roads, housing',
    description_ar: 'تعهّد ألّا يبقى ملف الخدمات رهين وعود مؤجلة. في النصف الأول من ٢٠٢٦ ذهب نحو ٨٥٪ من الإنفاق إلى الرواتب والاستحقاقات، مقابل ٢٫٥ تريليون دينار فقط للاستثمار.',
    description_en: 'Pledged that services would no longer be hostage to deferred promises. In H1 2026 about 85% of spending went to salaries and entitlements versus IQD 2.5 trillion for investment.',
    category: 'infrastructure',
    status: 'stalled',
    date_promised: '2026-05-16',
    deadline: '2027-05-14',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'تشكيل حكومة كاملة وملء الحقائب الشاغرة',
    title_en: 'Complete the cabinet — fill vacant portfolios',
    description_ar: 'أُقرّت الحكومة بـ١٤ وزيراً من ٢٣. الشواغر تشمل الداخلية والدفاع وحقائب سيادية وتنموية. حكومة ناقصة لا تُحاسب كحكومة كاملة — وهذا جزء من التصميم لا عارضه.',
    description_en: 'The government was sworn in with 14 of 23 ministers. Vacancies include Interior and Defence. A partial cabinet cannot be held to a full programme — and that is part of the design, not an accident.',
    category: 'general',
    status: 'in_progress',
    date_promised: '2026-05-14',
    deadline: '2026-06-14',
    source_url: 'https://www.aljazeera.com/news/2026/5/14/iraqs-parliament-approves-new-ali-al-zaidi-government',
  },
  {
    official_slug: 'ali-al-zaidi',
    title_ar: 'إصلاح التعليم والرعاية الصحية',
    title_en: 'Education and healthcare improvement',
    description_ar: 'وعود متكررة بتطوير المناهج والمستشفيات. من دون موازنة استثمارية ذات أولوية، تبقى هذه البنود خطاباً فوق إنفاق تشغيلي يبتلع الفائض.',
    description_en: 'Repeated pledges to upgrade curricula and hospitals. Without a prioritised investment budget, these remain speeches sitting on top of an operating bill that consumes the surplus.',
    category: 'healthcare',
    status: 'promised',
    date_promised: '2026-05-16',
    deadline: '2027-05-14',
    source_url: 'https://rudaw.net/english/middleeast/iraq/160520261',
  },
  {
    official_slug: 'faleh-sari',
    title_ar: 'إغلاق عجز النصف الأول من ٢٠٢٦',
    title_en: 'Close the H1 2026 fiscal deficit',
    description_ar: 'وزارة المالية: إيرادات نحو ٣٥٫٩ تريليون دينار مقابل إنفاق نحو ٥٧٫٢ تريليوناً في النصف الأول — عجز يفوق ٢١ تريليون دينار (نحو ١٦ مليار دولار). ٨٥٪ من الإنفاق رواتب واستحقاقات.',
    description_en: 'Finance Ministry: ~IQD 35.9tn revenue vs ~IQD 57.2tn spending in H1 — a deficit above IQD 21tn (~$16bn). Salaries and entitlements were 85% of expenditure.',
    category: 'economy',
    status: 'failed',
    date_promised: '2026-05-14',
    deadline: '2026-06-30',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
    notes_ar: 'الأرقام من بيانات الوزارة كما نقلتها روداو. التوثيق ≠ إدانة شخصية — هذا سجل أداء مالي عام.',
    notes_en: 'Figures from ministry data as reported by Rudaw. Documentation is not a personal conviction — this is a public fiscal performance record.',
  },
  {
    official_slug: 'faleh-sari',
    title_ar: 'صرف رواتب القطاع العام في مواعيدها',
    title_en: 'Pay public-sector salaries on schedule',
    description_ar: 'الوزارة تحتاج نحو ٧٫٧–٧٫٨ تريليون دينار شهرياً للرواتب. أُقرت أزمة السيولة في يوليو وتأخرت جداول. الوزير ينفي شائعات التأخير ٤٥ يوماً ويؤكّد تأمين الرواتب — والجدول على الأرض هو الاختبار.',
    description_en: 'The ministry needs about IQD 7.7–7.8tn a month for payroll. A liquidity crunch was confirmed in July and schedules slipped. The minister rejects 45-day delay rumours and says salaries are secured — the calendar on the ground is the test.',
    category: 'economy',
    status: 'stalled',
    date_promised: '2026-05-14',
    deadline: '2026-12-31',
    source_url: 'https://rudaw.net/english/categories/economic/1078991',
  },
  {
    official_slug: 'faleh-sari',
    title_ar: 'توسيع القاعدة الضريبية من الخطاب إلى التحصيل',
    title_en: 'Turn the tax base from a list into collections',
    description_ar: 'الوزير: ٣٨٠٠ فرد وشركة كبرى مصنَّفون كمكلّفين كبار، و١٣٠٠ فقط ملتزمون. بلا ضريبة تُحصَّل، يبقى النفط هو الدولة.',
    description_en: 'The minister identified 3,800 large taxpayers; only 1,300 were complying. Without collections, oil remains the state.',
    category: 'economy',
    status: 'stalled',
    date_promised: '2026-05-14',
    deadline: '2026-12-31',
    source_url: 'https://rudaw.net/english/categories/economic/1078991',
  },
  {
    official_slug: 'faleh-sari',
    title_ar: 'موازنة برامج وأداء بدل موازنة بنود',
    title_en: 'Move from line-item spending to a programme budget',
    description_ar: 'طلب الوزير من دائرة الموازنة الإسراع في موازنة برامج وأداء. الفكرة صحيحة. تنفيذها بلا قانون موازنة لعام ٢٠٢٦ يحوّلها إلى مشروع إداري فوق فراغ تشريعي.',
    description_en: 'The minister told the budget department to accelerate a programme-and-performance budget. The idea is right. Doing it with no 2026 budget law leaves a management project sitting on a legislative hole.',
    category: 'economy',
    status: 'in_progress',
    date_promised: '2026-05-14',
    deadline: '2026-12-31',
    source_url: 'https://en.964media.com/51081/',
  },
  {
    official_slug: 'basim-mohammed',
    title_ar: 'استعادة صادرات النفط إلى مستويات ما قبل الأزمة',
    title_en: 'Restore oil exports to pre-crisis volumes',
    description_ar: 'صادرات مايو–يونيو ٢٠٢٦ نحو ٣٢٫١ مليون برميل (حوالي ٥٢٦ ألف ب/ي) مقابل نحو ٣٫٣ مليون ب/ي قبل الحرب الإقليمية. أكثر من ٩٠٪ من الإيرادات الاتحادية كانت نفطية في الظروف العادية — هذا ليس تنوعاً، هذا انكشاف.',
    description_en: 'May–June 2026 exports were about 32.1 million barrels (~526k bpd) versus ~3.3 million bpd before the regional war. Oil is normally over 90% of federal revenue. That is not diversification. It is exposure.',
    category: 'economy',
    status: 'stalled',
    date_promised: '2026-05-14',
    deadline: '2026-12-31',
    source_url: 'https://en.964media.com/51081/',
  },
  {
    official_slug: 'haibat-al-halbousi',
    title_ar: 'تمرير موازنة ٢٠٢٦ بدل القفز إلى ٢٠٢٧',
    title_en: 'Pass a 2026 budget instead of skipping to 2027',
    description_ar: 'مجلس النواب تجاوز سنة مالية كاملة. رقابة بلا قانون موازنة هي رقابة على شيكات موقعة مسبقاً.',
    description_en: 'The Council of Representatives skipped an entire fiscal year. Oversight without a budget law is oversight of cheques already signed.',
    category: 'economy',
    status: 'failed',
    date_promised: '2025-12-29',
    deadline: '2026-03-31',
    source_url: 'https://en.964media.com/51739/',
  },
]

export const SEED_METRICS: SeedMetric[] = [
  {
    slug: 'h1-2026-fiscal-deficit',
    name_ar: 'عجز الموازنة — النصف الأول ٢٠٢٦',
    name_en: 'Fiscal deficit — H1 2026',
    description_ar: 'إنفاق أعلى من الإيرادات بأكثر من ١٦ مليار دولار في ستة أشهر، بحسب بيانات وزارة المالية كما نقلتها روداو.',
    description_en: 'Spending exceeded revenue by more than $16bn in six months, per Finance Ministry figures reported by Rudaw.',
    value: 16e9,
    unit: 'USD',
    year: 2026,
    trend: 'down',
    category: 'economy',
    source_name: 'Iraqi Ministry of Finance / Rudaw',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
  },
  {
    slug: 'h1-2026-salary-share',
    name_ar: 'حصة الرواتب من الإنفاق — ن١ ٢٠٢٦',
    name_en: 'Salary share of spending — H1 2026',
    description_ar: '٤٨٫٧٦ تريليون دينار رواتب واستحقاقات من أصل إنفاق إجمالي جعل النسبة نحو ٨٥٪. الاستثمار ٢٫٥ تريليون فقط.',
    description_en: 'IQD 48.76tn in salaries and entitlements — about 85% of spending. Investment was only IQD 2.5tn.',
    value: 85,
    unit: '%',
    year: 2026,
    previous_value: null,
    trend: 'up',
    category: 'economy',
    source_name: 'Iraqi Ministry of Finance / Rudaw',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
  },
  {
    slug: 'monthly-wage-bill',
    name_ar: 'فاتورة الرواتب الشهرية',
    name_en: 'Monthly public wage bill',
    description_ar: '٧٫٧ تريليون دينار شهرياً لرواتب ومدفوعات تمسّ نحو ٤٠ مليون عراقي، بحسب مستشار رئيس الوزراء مظهر محمد صالح.',
    description_en: 'IQD 7.7tn a month in salaries and related payments touching some 40 million Iraqis, per PM adviser Mazhar Mohammed Saleh.',
    value: 5.88e9,
    unit: 'USD',
    year: 2026,
    trend: 'stable',
    category: 'economy',
    source_name: '964 Media / PM financial adviser',
    source_url: 'https://en.964media.com/51739/',
  },
  {
    slug: 'oil-export-crisis-bpd',
    name_ar: 'صادرات النفط — مايو/يونيو ٢٠٢٦',
    name_en: 'Oil exports — May/June 2026',
    description_ar: 'نحو ٥٢٦ ألف برميل يومياً مقابل نحو ٣٫٣ مليون قبل الأزمة الإقليمية. النفط ما زال عمود الإيرادات.',
    description_en: 'About 526,000 barrels per day versus ~3.3 million before the regional crisis. Oil remains the revenue column.',
    value: 526000,
    unit: 'bpd',
    year: 2026,
    previous_value: 3300000,
    trend: 'down',
    category: 'economy',
    source_name: '964 Media',
    source_url: 'https://en.964media.com/51081/',
  },
  {
    slug: 'h1-2026-oil-revenue-share',
    name_ar: 'حصة النفط من الإيرادات — ن١ ٢٠٢٦',
    name_en: 'Oil share of revenue — H1 2026',
    description_ar: '٢٨٫٥ تريليون دينار نفطي من أصل ٣٥٫٩ تريليوناً (~٨٠٪). الارتفاع النسبي للإيراد غير النفطي جاء من انهيار النفط لا من نهضة ضريبية.',
    description_en: 'IQD 28.5tn oil of IQD 35.9tn total (~80%). The relative rise in non-oil revenue is an oil collapse, not a tax renaissance.',
    value: 80,
    unit: '%',
    year: 2026,
    previous_value: 92,
    trend: 'down',
    category: 'economy',
    source_name: 'Iraqi Ministry of Finance / Rudaw',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
  },
  {
    slug: 'budget-breakeven-oil',
    name_ar: 'سعر التعادل النفطي للموازنة',
    name_en: 'Budget break-even oil price',
    description_ar: 'قراءة المنبر التاريخية: دون نحو ٦٥ دولاراً للبرميل يدخل العراق عجزاً هيكلياً. تقديرات ٢٠٢٧ تتحدث عن ٥٠–٦٠ دولاراً في مشروع الموازنة — أي هندسة تنهار عند أول صدمة.',
    description_en: 'Al-Minbar’s working figure: below about $65/barrel Iraq faces a structural deficit. 2027 budget talk of $50–60 is engineering that fails at the first shock.',
    value: 65,
    unit: 'USD/bbl',
    year: 2026,
    trend: 'stable',
    category: 'economy',
    source_name: 'Al-Minbar / public budget reporting',
    source_url: 'https://en.964media.com/51739/',
  },
  {
    slug: 'large-taxpayer-compliance',
    name_ar: 'التزام كبار المكلّفين ضريبياً',
    name_en: 'Large-taxpayer compliance',
    description_ar: '١٣٠٠ ملتزم من أصل ٣٨٠٠ مكلّف كبير حددتهم وزارة المالية — نحو ٣٤٪.',
    description_en: '1,300 complying of 3,800 large taxpayers identified by the Finance Ministry — about 34%.',
    value: 34,
    unit: '%',
    year: 2026,
    trend: 'down',
    category: 'governance',
    source_name: 'Iraqi Ministry of Finance / Rudaw',
    source_url: 'https://rudaw.net/english/categories/economic/1078991',
  },
  {
    slug: 'h1-2026-investment-share',
    name_ar: 'حصة الاستثمار من الإنفاق — ن١ ٢٠٢٦',
    name_en: 'Investment share of spending — H1 2026',
    description_ar: '٢٫٥ تريليون دينار استثمار من إنفاق يتجاوز ٥٧ تريليوناً — أقل من ٥٪. الباقي تشغيل.',
    description_en: 'IQD 2.5tn investment of more than IQD 57tn spending — under 5%. The rest is operations.',
    value: 4.4,
    unit: '%',
    year: 2026,
    trend: 'down',
    category: 'economy',
    source_name: 'Iraqi Ministry of Finance / Rudaw',
    source_url: 'https://rudaw.net/english/categories/economic/1078885',
  },
  {
    slug: 'cpi',
    name_ar: 'مؤشر مدركات الفساد',
    name_en: 'Corruption Perceptions Index',
    description_ar: 'تصنيف منظمة الشفافية الدولية. الترتيب الأدنى يعني فساداً أعلى في القطاع العام.',
    description_en: 'Transparency International ranking. Lower rank = more perceived public-sector corruption.',
    value: 23,
    unit: 'score/100',
    year: 2024,
    global_rank: 140,
    total_countries: 180,
    trend: 'stable',
    category: 'governance',
    source_name: 'Transparency International',
    source_url: 'https://www.transparency.org/en/cpi',
  },
]

export const SEED_CASES: SeedCase[] = [
  {
    official_slug: null,
    title_ar: 'مداهمات المنطقة الخضراء — يونيو ٢٠٢٦',
    title_en: 'Green Zone anti-corruption raids — June 2026',
    description_ar: 'تقارير علنية عن اعتقال عشرات المسؤولين الحاليين والسابقين في المنطقة الخضراء، بينهم نائب وزير النفط. الملفات قيد المتابعة. التوثيق الصحفي ليس حكماً قضائياً — وغياب الأحكام اللاحقة هو أيضاً بيان.',
    description_en: 'Public reporting of dozens of current and former officials detained in Green Zone raids, including the deputy oil minister. Files remain to be watched. Press documentation is not a verdict — and a later absence of verdicts is also a statement.',
    amount_usd: null,
    date_reported: '2026-06-15',
    source_urls: [
      'https://www.theatlantic.com/national-security/2026/07/iraq-ali-alzaidi-iran-war-trump/688009/',
      'https://abc7ny.com/post/trump-rolls-white-house-welcome-mat-new-iraqi-prime-minister-ali-al-zaidi/19505392/',
    ],
    status: 'under_investigation',
    evidence_level: 'medium',
    case_type: 'financial',
    is_published: true,
  },
]
