// Sample article data — bilingual, with TL;DR + margin stats + section breaks
window.ARTICLES = [
  {
    slug: 'muwazanat-2025',
    topic_ar: 'السياسة الاقتصادية',
    topic_en: 'Economic Policy',
    title_ar: 'الموازنة العراقية 2025: وهم الإصلاح وحقيقة الاتكاء على النفط',
    title_en: 'The Iraqi Budget 2025: The Illusion of Reform',
    excerpt_ar: 'قراءة نقدية في بنية الموازنة الاتحادية لعام 2025 وما تكشفه من استمرار الاعتماد الهيكلي على النفط وغياب إرادة الإصلاح الحقيقي.',
    excerpt_en: 'A critical reading of the 2025 federal budget and what it reveals about structural oil dependency and the absence of reform.',
    author_ar: 'طارق الراشد',
    author_en: 'Tariq Al-Rashid',
    date: '2026-04-15',
    minutes: 9,
    featured: true,
    pull_ar: 'الدولة الريعية لا تصلح نفسها من تلقاء ذاتها.',
    pull_en: 'The rentier state does not reform itself.',
    tldr_ar: [
      '٩٣٪ من الإيرادات تأتي من النفط — والحكومة تعِد بالتنويع منذ عقدين',
      'أكثر من ٤ ملايين موظف حكومي، والقطاع الخاص يساهم بأقل من ٤٪ في الناتج المحلي',
      'الفساد يبتلع المليارات من العقود الحكومية قبل أن تُبنى مدرسة واحدة',
      'الإصلاح الحقيقي يحتاج ضريبة وإرادة سياسية — وكلاهما في إجازة',
      'الخلاصة: وثيقة محاصصة، لا خطة تنمية',
    ],
    tldr_en: [
      '93% of revenues are oil money. Diversification promised for two decades.',
      '4M+ public sector workers. Private sector under 4% of GDP. Math doesn\u2019t work.',
      'Corruption swallows billions in contracts before a school gets built.',
      'Real reform needs tax + political will. Both on indefinite leave.',
      'Bottom line: a power-sharing document dressed as a budget.',
    ],
    body_ar: [
      { type: 'lede', text: 'حين صادق مجلس النواب العراقي على الموازنة الاتحادية لعام 2025 في أواخر عام 2024، كان الخطاب الرسمي يتحدث عن "مرحلة جديدة" من التنويع الاقتصادي. غير أن قراءة متأنية للأرقام تكشف عن حقيقة مغايرة تماماً.' },
      { type: 'p', text: 'ما يزيد على 93% من الإيرادات المتوقعة مصدرها النفط الخام، وهي نسبة لم تتغير جوهرياً منذ عقود. المشكلة ليست في الرقم وحده، بل في الأنماط البنيوية التي يعكسها. فالقطاع الخاص غير النفطي يساهم بأقل من 4% في الناتج المحلي الإجمالي، فيما يستوعب القطاع الحكومي أكثر من أربعة ملايين موظف.', margin: { side: 'right', label: 'حصة النفط', number: '٩٣٪', unit: 'من الإيرادات', note: 'موازنة 2025 الاتحادية — مكتب رئاسة الوزراء' } },
      { type: 'p', text: 'وحين يهبط سعر النفط إلى ما دون خمسة وستين دولاراً للبرميل، يجد العراق نفسه وجهاً لوجه أمام عجز مالي هيكلي لا مفر منه. هذه ليست أزمة عابرة — إنها هندسة اقتصادية مصممة للانهيار عند أول صدمة سعرية.', margin: { side: 'left', label: 'سعر التعادل', number: '$65', unit: 'للبرميل', note: 'الحد الأدنى لتوازن الموازنة' } },
      { type: 'stat', label: 'القطاع الخاص', figure: '< ٤٪', desc: 'مساهمة القطاع الخاص غير النفطي في الناتج المحلي الإجمالي. اقتصاد بلا قطاع خاص ليس اقتصاداً.' },
      { type: 'h2', text: 'ما يغيب أهم مما يحضر' },
      { type: 'p', text: 'لا ترى في الموازنة رؤية متكاملة لتطوير البنية التحتية الصناعية، ولا استراتيجية واضحة لتحفيز الاستثمار الخاص في الزراعة والتصنيع والتقنية. ثمة مخصصات للمشاريع، نعم — لكنها تتوزع وفق منطق المحاصصة السياسية والجغرافية، لا وفق أولويات التنمية الاقتصادية المستدامة.' },
      { type: 'pull', text: 'الدولة الريعية لا تصلح نفسها من تلقاء ذاتها.' },
      { type: 'p', text: 'منطق توزيع ريع النفط — الذي يمنح الحكومة شرعيتها عبر رواتب القطاع العام والدعومات لا عبر الكفاءة والإنتاج — يُفرز نخباً سياسية لا مصلحة لها في بناء اقتصاد حقيقي منتج. لأن الاقتصاد الحقيقي يستوجب محاسبة حقيقية، وهو ما تتجنبه منظومة الحكم الراهنة.', margin: { side: 'right', label: 'موظفو القطاع العام', number: '٤+', unit: 'مليون موظف', note: 'مقابل أقل من 600 ألف في القطاع الخاص الرسمي' } },
      { type: 'h2', text: 'الفساد بالأرقام' },
      { type: 'p', text: 'الفساد المؤسسي لا يزال يُجرف نسباً كبيرة من الإنفاق الحكومي قبل أن تصل إلى مستحقيها. التقارير الرقابية تشير إلى خسائر مالية ناجمة عن الفساد في المشتريات والعقود تُقدَّر بمليارات الدولارات سنوياً. ليست أرقاماً مجردة — إنها مدارس لم تُبنَ، ومستشفيات لم تُجهَّز، وشبكات مياه لم تُصلَح.' },
      { type: 'p', text: 'الإصلاح الذي يستحق هذا الاسم يبدأ من الضريبة لا من النفط: بناء منظومة ضريبية عادلة وفعّالة على الأرباح والثروات، وتحرير بيئة الأعمال من الروتين، وربط الإنفاق بمؤشرات الأداء. غير أن هذا يتطلب إرادة سياسية لم تتشكل بعد.' },
      { type: 'p', text: 'في المحصلة، موازنة 2025 ليست وثيقة تنمية — إنها وثيقة بقاء سياسي تُعيد توزيع ريع النفط بين المتنافسين على السلطة. وما لم تتغير هذه المعادلة البنيوية، سيبقى الحديث عن التنويع ترفاً خطابياً.' },
    ],
    body_en: [
      { type: 'lede', text: 'When Iraq\u2019s Council of Representatives ratified the 2025 federal budget in late 2024, the official narrative spoke of a "new phase" of diversification. A careful reading of the figures reveals a different reality.' },
      { type: 'p', text: 'Over 93% of projected revenues come from crude oil — a ratio that has not meaningfully changed in decades. The problem lies not in this figure alone, but in the structural patterns it reflects. The non-oil private sector contributes less than 4% to GDP, while the public sector employs more than four million civil servants.', margin: { side: 'right', label: 'Oil revenue share', number: '93%', unit: 'of total', note: 'Federal Budget 2025, PM Office' } },
      { type: 'p', text: 'When oil falls below sixty-five dollars a barrel, Iraq faces structural fiscal deficit with no exit. This is not a passing crisis — it is economic engineering designed to collapse at the first price shock.', margin: { side: 'left', label: 'Break-even', number: '$65', unit: 'per barrel', note: 'Minimum for budget balance' } },
      { type: 'stat', label: 'Private sector', figure: '< 4%', desc: 'Non-oil private sector contribution to GDP. An economy without a private sector is not an economy.' },
      { type: 'h2', text: 'What is absent matters most' },
      { type: 'p', text: 'There is no coherent vision for industrial infrastructure, no clear strategy for private investment in agriculture, manufacturing, or technology. There are project allocations — but distributed by the logic of political and geographic power-sharing, not sustainable development.' },
      { type: 'pull', text: 'The rentier state does not reform itself.' },
      { type: 'p', text: 'The logic of distributing oil rents — granting the government legitimacy through public-sector salaries and subsidies rather than efficiency and production — produces political elites with no interest in building a productive economy. Because real economies demand real accountability, which the current system avoids.', margin: { side: 'right', label: 'Public sector', number: '4M+', unit: 'employees', note: 'vs. <600K in formal private sector' } },
      { type: 'h2', text: 'Corruption by the numbers' },
      { type: 'p', text: 'Institutional corruption continues to drain significant portions of government spending before it reaches its beneficiaries. Oversight reports cite losses estimated at billions annually. These are not abstract numbers — they are schools not built, hospitals not equipped, water networks not repaired.' },
      { type: 'p', text: 'Reform worthy of the name begins with taxation, not oil: building a fair tax system on profits and wealth, liberating business from bureaucracy, and linking spending to measurable outcomes. This requires political will that has yet to materialize.' },
      { type: 'p', text: 'In sum, the 2025 budget is not a development document — it is a political survival document redistributing oil rents among those competing for power. Until this equation changes, talk of diversification will remain rhetorical luxury.' },
    ],
  },
  {
    slug: 'kahraba-baghdad',
    topic_ar: 'البنية التحتية',
    topic_en: 'Infrastructure',
    title_ar: 'الكهرباء في بغداد: عشرون سنة من الوعود وانقطاع لا يُحلّ',
    title_en: 'Baghdad Electricity: Twenty Years of Promises, Outages That Won\u2019t End',
    excerpt_ar: 'لماذا تنفق الحكومة العراقية مليارات الدولارات على قطاع الكهرباء وتبقى المنظومة الوطنية عاجزة عن تلبية الطلب؟',
    excerpt_en: 'Why does the Iraqi government spend billions on electricity while the national grid still fails to meet demand?',
    author_ar: 'طارق الراشد',
    author_en: 'Tariq Al-Rashid',
    date: '2026-03-22',
    minutes: 7,
    pull_ar: 'الكهرباء عندنا ليست مشكلة هندسية — هي مشكلة سياسية ترتدي بزة المهندس.',
    pull_en: 'Our electricity is not an engineering problem. It is a political problem in an engineer\u2019s uniform.',
    tldr_ar: [
      'أُنفق أكثر من ٨٠ مليار دولار على القطاع منذ ٢٠٠٣ — والمولّدات الخاصة لا تزال تعمل',
      'العجز في الذروة الصيفية يبلغ ٨ آلاف ميغاواط — أي مدينة كاملة بلا تيار',
      'الفقد في الشبكة يتجاوز ٤٠٪ — نصفه فني، نصفه سرقة منظَّمة',
      'العقود تمر عبر سبع طبقات من الوسطاء قبل أن تصل إلى المهندس',
      'الخلاصة: المشكلة ليست في الكهرباء، بل في من يستفيد من بقائها معطوبة',
    ],
    tldr_en: [
      'Over $80B spent on the sector since 2003 — private generators still hum.',
      'Peak summer gap: 8,000 MW. An entire city, dark.',
      'Grid losses exceed 40% — half technical, half organized theft.',
      'Contracts pass through seven layers of intermediaries before reaching the engineer.',
      'Bottom line: the problem isn\u2019t electricity. It\u2019s who profits from it being broken.',
    ],
    body_ar: [
      { type: 'lede', text: 'في صيف ٢٠٢٣، حين تجاوزت الحرارة في بغداد خمسين درجة مئوية، كانت العائلات تتناوب على النوم أمام مولّدات الحي. لم يكن هذا مشهداً استثنائياً — بل المشهد الافتراضي منذ عقدين. خلال هذه العقود، أُنفق على قطاع الكهرباء ما يفوق ثمانين مليار دولار. والسؤال ليس "أين ذهب المال؟" — السؤال هو: لماذا يستمر النظام في الفشل بنفس الطريقة كل عام؟' },
      { type: 'p', text: 'الإجابة الرسمية معتادة: نقص الغاز، الإرهاب، الطقس، ارتفاع الطلب. كلها صحيحة جزئياً. وكلها تتجنب القلب: الكهرباء في العراق لم تُصمَّم لتعمل — صُمِّمت لتُموَّل. كل أزمة طاقة هي مناقصة جديدة، وكل مناقصة هي عمولة، وكل عمولة هي شريحة من شبكة سياسية تحتاج التغذية.', margin: { side: 'right', label: 'الإنفاق التراكمي', number: '$80+', unit: 'مليار', note: 'وزارة الكهرباء، تقديرات تراكمية ٢٠٠٣–٢٠٢٤' } },
      { type: 'p', text: 'انظر إلى الفجوة بين العرض والطلب في ذروة الصيف: تصل إلى ثمانية آلاف ميغاواط. هذا ليس عجزاً — هذا حجم مدينة عراقية متوسطة بلا كهرباء على الإطلاق. والحلول الفنية لها معروفة منذ خمسة عشر عاماً: محطات دورة مركبة بكفاءة عالية، شبكة نقل جهد فائق العالي، نظام عدّاد ذكي يُنهي السرقة، استثمار جدي في الطاقة الشمسية حيث الشمس مجانية تسعة أشهر في السنة.', margin: { side: 'left', label: 'فجوة الذروة', number: '٨,٠٠٠', unit: 'ميغاواط', note: 'صيف ٢٠٢٣ — تقرير الشبكة الوطنية' } },
      { type: 'stat', label: 'الفقد في الشبكة', figure: '> ٤٠٪', desc: 'نصفه فقد فني بسبب شبكة متهالكة، نصفه سرقة وتعليق غير قانوني. في الدول المماثلة لا يتجاوز ١٢٪.' },
      { type: 'h2', text: 'هندسة الفشل المنظَّم' },
      { type: 'p', text: 'لنأخذ عقداً نموذجياً: محطة توليد بقدرة خمسمئة ميغاواط، قيمتها التعاقدية حوالي ٧٥٠ مليون دولار. تخرج الكلفة الفعلية للبناء أقل بكثير — ربما خمسمئة مليون. الفارق لا يختفي. يتوزع عبر سلسلة من المقاولين الثانويين، الوكلاء المحليين، الشركاء "المطلوبين" بحكم العرف السياسي، والاستشاريين الذين لا يستشيرون شيئاً.', margin: { side: 'right', label: 'طبقات الوسطاء', number: '٧', unit: 'في عقد واحد', note: 'مراجعة لعقد محطة توليد نموذجي ٢٠٢١' } },
      { type: 'pull', text: 'الكهرباء عندنا ليست مشكلة هندسية — هي مشكلة سياسية ترتدي بزة المهندس.' },
      { type: 'p', text: 'حين تنتهي المحطة من البناء — متأخرة بسنتين عن الموعد المتعاقَد عليه — تكتشف الوزارة أن خط الغاز الذي يفترض أن يغذيها لم يُمدَّ. لماذا؟ لأن عقد خط الغاز كان مع وزارة أخرى، تتحكم بها كتلة سياسية أخرى، لم تُحسَم حصصها بعد. تنتظر المحطة الجديدة شهوراً، ثم سنوات. وحين تشتغل، تشتغل بكفاءة نصف المعلَنة لأن المعدات وصلت ناقصة.' },
      { type: 'h2', text: 'لماذا تنجح المولّدة، ويفشل النظام؟' },
      { type: 'p', text: 'لاحظ الآن المفارقة: مولّدة الحي — تلك التي يديرها شاب من البلد، بدون شهادة هندسية، بدون عقود حكومية — تعمل. تعمل سنة كاملة. صاحبها يصلحها بنفسه، يشتري وقودها من السوق، يحصِّل ثمنها من الجيران بالكاش. الاقتصاد بسيط: خدمة، ثمن، مسؤولية مباشرة. لا وسطاء، لا محاصصة.', margin: { side: 'left', label: 'المولّدات الخاصة', number: '٢.٥+', unit: 'مليون مشترك', note: 'تقدير غير رسمي — اتحاد جمعيات أصحاب المولّدات' } },
      { type: 'p', text: 'هذه ليست دعوة إلى الخصخصة الكاملة — فالكهرباء سلعة استراتيجية لا يجوز تركها لمنطق السوق وحده. لكنها مرآة. تقول لنا إن المشكلة ليست في إمكانية تشغيل خدمة كهرباء في العراق. المشكلة في النموذج الإداري الذي يُصرّ عليه النظام السياسي لأن أي بديل يهدِّد منظومة الريع.' },
      { type: 'h2', text: 'ما الذي يلزم فعلاً' },
      { type: 'p', text: 'الإصلاح الذي يستحق هذا الاسم لا يبدأ من بناء محطات جديدة. يبدأ من ثلاث نقاط: استقلالية مالية وإدارية كاملة لشركة الكهرباء عن الوزارة؛ نظام عقود مفتوح ومنشور علناً مع آلية اعتراض قضائي سريع؛ وتسعيرة كهرباء تعكس الكلفة الحقيقية، مع دعم مباشر للأسر الفقيرة بدلاً من الدعم العام الذي يسرق منه القادرون أكثر مما يستفيد منه المحتاجون.' },
      { type: 'p', text: 'كل هذه الحلول معروفة. كلها مكتوبة في تقارير البنك الدولي، ومستشاري وزارة الكهرباء، ولجان الإصلاح المتعاقبة. لم تُطبَّق ليس لأنها صعبة فنياً — بل لأن تطبيقها يعني إنهاء آلية تمويل سياسية كاملة. وهنا يقف الإصلاح، عند الحد الذي يعجز الخطاب الرسمي عن تجاوزه.' },
    ],
    body_en: [
      { type: 'lede', text: 'In the summer of 2023, when Baghdad temperatures crossed fifty degrees Celsius, families took turns sleeping by the neighborhood generator. This was not exceptional — it was the default, sustained for two decades. Across those decades, more than eighty billion dollars has flowed into the electricity sector. The question is not "where did the money go?" The question is: why does the system keep failing in exactly the same way every year?' },
      { type: 'p', text: 'The official answer is familiar: gas shortages, terrorism, weather, rising demand. Each is partially true. Each avoids the core. Iraqi electricity was not designed to work — it was designed to be funded. Every energy crisis is a fresh tender, every tender a commission, every commission a slice that feeds a political network.', margin: { side: 'right', label: 'Cumulative spend', number: '$80B+', unit: 'since 2003', note: 'Ministry of Electricity, cumulative estimates 2003–2024' } },
      { type: 'p', text: 'Look at the supply-demand gap at peak summer: eight thousand megawatts. That is not a deficit — that is the size of a mid-sized Iraqi city with no electricity at all. The technical fixes have been known for fifteen years: high-efficiency combined-cycle plants, very-high-voltage transmission, smart metering to end theft, serious investment in solar where the sun is free nine months a year.', margin: { side: 'left', label: 'Peak gap', number: '8,000', unit: 'MW', note: 'Summer 2023 — National Grid report' } },
      { type: 'stat', label: 'Grid losses', figure: '> 40%', desc: 'Half technical, due to a decaying network. Half theft and illegal hookups. In comparable countries, this number is under 12%.' },
      { type: 'h2', text: 'The engineering of organized failure' },
      { type: 'p', text: 'Take a typical contract: a 500 MW generation plant, contract value around $750 million. The actual build cost is much lower — perhaps $500 million. The gap does not vanish. It distributes across subcontractors, local agents, "required" partners by political custom, and consultants who consult on nothing.', margin: { side: 'right', label: 'Layers of intermediaries', number: '7', unit: 'per contract', note: 'Audit of a representative 2021 generation contract' } },
      { type: 'pull', text: 'Our electricity is not an engineering problem. It is a political problem in an engineer\u2019s uniform.' },
      { type: 'p', text: 'When the plant is finally finished — two years late — the ministry discovers the gas line that should feed it was never laid. Why? Because the gas-line contract sat with a different ministry, controlled by a different political bloc, whose share had not been settled. The new plant waits months, then years. When it finally runs, it runs at half its declared efficiency because the equipment arrived incomplete.' },
      { type: 'h2', text: 'Why does the generator succeed, and the system fail?' },
      { type: 'p', text: 'Note the paradox. The neighborhood generator — run by a young man with no engineering degree, no government contract — works. It runs all year. The owner repairs it himself, buys his own fuel, collects his own cash. The economics are simple: service, price, direct responsibility. No intermediaries. No quotas.', margin: { side: 'left', label: 'Private generators', number: '2.5M+', unit: 'subscribers', note: 'Informal estimate — Generator Owners Association' } },
      { type: 'p', text: 'This is not an argument for full privatization — electricity is a strategic good and cannot be left to market logic alone. But it is a mirror. It tells us the problem is not the feasibility of running power in Iraq. The problem is the management model the political system insists on, because any alternative threatens the rent network.' },
      { type: 'h2', text: 'What it would actually take' },
      { type: 'p', text: 'Reform worthy of the name does not start with building new plants. It starts with three things: full financial and administrative independence for the electricity company from the ministry; an open, publicly published contracting system with rapid judicial review; and tariffs that reflect real cost, with direct subsidies for poor families rather than blanket subsidies that benefit the wealthy more than the needy.' },
      { type: 'p', text: 'All of these solutions are known. All are written into World Bank reports, ministry consultants\u2019 binders, successive reform committees. They have not been applied not because they are technically hard — but because applying them means ending an entire political funding mechanism. And here reform stops, at the line official discourse cannot cross.' },
    ],
  },
  {
    slug: 'al-fasad-al-mu-assasi',
    topic_ar: 'مكافحة الفساد',
    topic_en: 'Anti-Corruption',
    title_ar: 'الفساد المؤسسي: ليس استثناءً بل آلية حكم',
    title_en: 'Institutional Corruption: Not an Exception, A Mechanism of Rule',
    excerpt_ar: 'الفساد في العراق ليس مرضاً عرضياً يصيب نظاماً سليماً — بل هو الآلية الأساسية التي يعمل بها النظام نفسه.',
    excerpt_en: 'Corruption in Iraq is not a passing affliction. It is the basic mechanism by which the system itself operates.',
    author_ar: 'طارق الراشد',
    author_en: 'Tariq Al-Rashid',
    date: '2026-03-08',
    minutes: 11,
    tldr_ar: ['الفساد ليس خللاً — هو وظيفة', 'هيئة النزاهة بلا أنياب حقيقية', 'الإصلاح يبدأ من تفكيك المحاصصة، لا من القوانين'],
    tldr_en: ['Corruption is not a bug — it\u2019s a feature', 'The Integrity Commission has no real teeth', 'Reform starts by dismantling sectarian quotas, not laws'],
  },
  {
    slug: 'al-mu-assasat-al-da-ifa',
    topic_ar: 'الإصلاح المؤسسي',
    topic_en: 'Institutional Reform',
    title_ar: 'مؤسسات بلا سلطة: لماذا تفشل الرقابة في العراق؟',
    title_en: 'Institutions Without Authority: Why Oversight Fails in Iraq',
    excerpt_ar: 'يمتلك العراق على الورق منظومة رقابية متكاملة — ديوان رقابة، هيئة نزاهة، لجان برلمانية. لماذا تفشل جميعها؟',
    excerpt_en: 'On paper, Iraq has a full oversight system. Why does every part of it fail?',
    author_ar: 'طارق الراشد',
    author_en: 'Tariq Al-Rashid',
    date: '2026-02-19',
    minutes: 8,
    tldr_ar: ['الرقابة بلا سلطة تنفيذية = ديكور', 'القضاء يخضع لذات القوى التي يفترض أن يحاسبها', 'الحل: استقلالية مالية وإدارية للهيئات الرقابية'],
    tldr_en: ['Oversight without enforcement = decoration', 'The judiciary answers to the same forces it should hold accountable', 'Solution: fiscal and administrative independence for oversight bodies'],
  },
  {
    slug: 'al-shabab-w-al-hijra',
    topic_ar: 'الشأن الاجتماعي',
    topic_en: 'Society',
    title_ar: 'هجرة العقول: حين يصبح المغادرة قراراً عقلانياً',
    title_en: 'The Brain Drain: When Leaving Becomes the Rational Choice',
    excerpt_ar: 'يغادر العراق سنوياً آلاف من خريجي الطب والهندسة والعلوم. هذه ليست خيانة — إنها قراءة دقيقة للواقع.',
    excerpt_en: 'Thousands of Iraq\u2019s doctors, engineers, and scientists leave each year. This is not betrayal — it is a clear reading of reality.',
    author_ar: 'طارق الراشد',
    author_en: 'Tariq Al-Rashid',
    date: '2026-01-30',
    minutes: 10,
    tldr_ar: ['أكثر من 70% من خريجي الطب يفكرون بالهجرة', 'الراتب ليس السبب الأول — البيئة المهنية هي', 'بقاء الكفاءات يتطلب مشروعاً وطنياً، لا شعارات'],
    tldr_en: ['Over 70% of medical graduates consider emigration', 'Salary isn\u2019t the top reason — the professional environment is', 'Retention requires a national project, not slogans'],
  },
];

window.SAMPLE_COMMENTS = {
  'kahraba-baghdad': [
    { id: 1, name_ar: 'مهند الجبوري', name_en: 'Muhannad Al-Jubouri', initial: 'م', date: '2026-03-23', body_ar: 'كمهندس عمل في وزارة الكهرباء لسبع سنوات، أؤكد كل كلمة. أسوأ ما في الأمر أن من يحاول العمل بصدق يُحاصَر — لا يُطرد، بل يُحاصَر حتى يستقيل.', body_en: 'As an engineer who worked in the ministry for seven years, I confirm every word. The worst part: those who try to work honestly are not fired — they are surrounded until they resign.' },
    { id: 2, name_ar: 'سارة الموسوي', name_en: 'Sarah Al-Mousawi', initial: 'س', date: '2026-03-24', body_ar: 'الفقرة عن المولّدة دقيقة جداً. السوق غير الرسمي يعمل لأن المساءلة فيه فورية. الدرس واضح، لكن لا أحد يريد سماعه.', body_en: 'The paragraph about the generator is precise. The informal market works because accountability there is immediate. The lesson is obvious, but no one wants to hear it.' },
  ],
  'muwazanat-2025': [
    { id: 1, name_ar: 'هدى الكاظمي', name_en: 'Huda Al-Kadhimi', initial: 'ه', date: '2026-04-16', body_ar: 'تحليل دقيق. أضيف إلى ذلك أن الموازنات السنوية أصبحت مفرغة من معناها — لا أحد في الوزارات يعمل وفق رؤية متعددة السنوات. الموازنة تُعدّ ثم تُنسى.', body_en: 'Sharp analysis. I\u2019d add that annual budgets have lost their meaning — no one in ministries works to a multi-year vision. Budgets are drafted and forgotten.' },
    { id: 2, name_ar: 'عمر سعيد', name_en: 'Omar Saeed', initial: 'ع', date: '2026-04-17', body_ar: 'النقطة المتعلقة بربط الإنفاق بمؤشرات الأداء جوهرية. لكن من سيقيس الأداء حين تكون الجهات الرقابية ذاتها جزءاً من المنظومة؟', body_en: 'The point about linking spending to performance indicators is essential. But who measures performance when oversight bodies are themselves part of the system?' },
    { id: 3, name_ar: 'ليلى الحلو', name_en: 'Layla Al-Hilou', initial: 'ل', date: '2026-04-18', body_ar: 'مقال يستحق القراءة مرتين. اللغة هادئة، لكن الحجة قاسية — وهذا تماماً ما نحتاجه.', body_en: 'Worth reading twice. The language is calm, but the argument is harsh — exactly what we need.' },
  ],
};
